name: testLab

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * *"

jobs:
  weather:
    strategy: 
      matrix:
        city: [London,Tokyo,NYC]
    runs-on: ubuntu-latest
    steps:
      - name: Fetch weather
        run: |
          CITY= "London"
          WEATHER=$(curl -s "wttr.in/$CITY?format=3")
          echo "Weather in $CITY: $WEATHER"

          echo "## $CITY Weather" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**$WEATHER**" >> $GITHUB_STEP_SUMMARY
