name: testLab

on:
  push:
    branches: [main]
  workflow_dispatch:
##  schedule:
##    - cron: "0 8 * * *"

jobs:
  weather:
    strategy: 
      matrix:
        city: [London,Tokyo,NYC]
    runs-on: ubuntu-latest
    steps:
      - name: Fetch weather
        run: |
          WEATHER=$(curl -s "wttr.in/${{ matrix.city }}?format=3")
          echo "Weather in ${{ matrix.city }}: $WEATHER"

          echo "## ${{ matrix.city }} Weather" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**$WEATHER**" >> $GITHUB_STEP_SUMMARY
      - uses: actions/upload-artifact@v4
        with:
          name: report
          path: out.txt
